services:
  frontend:
    image: marijahmed/clippr-frontend
    ports:
      - "80:80"
    networks:
      - clippr-net

  backend:
    image: marijahmed/clippr-backend
    ports:
      - "3000:3000"
    networks:
      - clippr-net
    env_file:
      - .env

networks:
  clippr-net:
    driver: bridge